// Film catalog for Madtape — AI-generated cinema archive
const FILMS = [
  {
    id: "kestrel-protocol",
    no: "MT-001",
    title: "The Kestrel Protocol",
    runtime: "94m",
    year: "2026",
    genre: "Speculative",
    model: "Sora-3.2 / Veo-4",
    seed: "0x9F2C·a17e",
    compute: "412 GPU·h",
    fps: "24",
    resolution: "3840×1612",
    aspect: "2.39:1",
    rating: 4.7,
    color: "#C84B1A",
    tone: "warm",
    synopsis: "A cartographer in a flooded delta receives instructions from a satellite that may not exist. The map redraws itself nightly.",
    prompt: "Bengal delta at golden hour, lone figure with brass instrument, water-level cinematography, Roger Deakins lighting, 35mm grain, deliberate pacing"
  },
  {
    id: "still-life-with-static",
    no: "MT-002",
    title: "Still Life with Static",
    runtime: "11m",
    year: "2026",
    genre: "Short / Experimental",
    model: "Runway Gen-4",
    seed: "0x4411·b2d9",
    compute: "38 GPU·h",
    fps: "30",
    resolution: "2160×2160",
    aspect: "1:1",
    rating: 4.2,
    color: "#E8DDB5",
    tone: "neutral",
    synopsis: "Six fruit bowls, one room, ninety years. The painter never appears.",
    prompt: "Dutch still life translated through CRT decay, time-lapse rot, single fixed lens, no human figures, dust motes"
  },
  {
    id: "longwave",
    no: "MT-003",
    title: "Longwave",
    runtime: "127m",
    year: "2025",
    genre: "Drama",
    model: "Veo-4 / Pika-2",
    seed: "0x77AA·c01f",
    compute: "892 GPU·h",
    fps: "24",
    resolution: "4096×1716",
    aspect: "2.39:1",
    rating: 4.9,
    color: "#1F3D5C",
    tone: "cool",
    synopsis: "A radio operator in 1962 Newfoundland intercepts a broadcast from her future self. She has six weeks to decide whether to answer.",
    prompt: "Cold Atlantic coast, mid-century interiors, anamorphic lens, Edward Hopper composition, low-key tungsten, slow dolly"
  },
  {
    id: "rind",
    no: "MT-004",
    title: "Rind",
    runtime: "22m",
    year: "2026",
    genre: "Horror / Folk",
    model: "Sora-3.2",
    seed: "0xDD09·77b3",
    compute: "104 GPU·h",
    fps: "25",
    resolution: "3840×2160",
    aspect: "16:9",
    rating: 4.4,
    color: "#3A2419",
    tone: "warm",
    synopsis: "An orchard in Devon refuses to be photographed. The crew tries anyway.",
    prompt: "Found-footage handheld, English orchard at dusk, super 16mm grain, no faces in focus, sound design driven by wind"
  },
  {
    id: "hyperion-fragments",
    no: "MT-005",
    title: "Hyperion, Fragments",
    runtime: "48m",
    year: "2026",
    genre: "Documentary",
    model: "Sora-3.2 / Kling-2",
    seed: "0x5C18·ee44",
    compute: "267 GPU·h",
    fps: "24",
    resolution: "3840×2160",
    aspect: "16:9",
    rating: 4.6,
    color: "#7A8C5C",
    tone: "neutral",
    synopsis: "Reconstructed visions from the lost notebooks of a 19th-century botanist who claimed to have walked into a painting.",
    prompt: "Botanical illustration cross-fading to live forest, archive photo plates, hand-drawn maps, soft narrator voice, Werner Herzog cadence"
  },
  {
    id: "marble-eye",
    no: "MT-006",
    title: "Marble Eye",
    runtime: "8m",
    year: "2026",
    genre: "Music Video",
    model: "Pika-2",
    seed: "0xB201·39ac",
    compute: "21 GPU·h",
    fps: "60",
    resolution: "2560×1440",
    aspect: "16:9",
    rating: 3.9,
    color: "#A8B8C8",
    tone: "cool",
    synopsis: "A statue learns to blink. A city responds in kind.",
    prompt: "Roman marble, slow blooming saturation, choreographed urban crowd, vertical scaffolding, brass-heavy score"
  },
  {
    id: "sundown-arithmetic",
    no: "MT-007",
    title: "Sundown Arithmetic",
    runtime: "73m",
    year: "2026",
    genre: "Western",
    model: "Veo-4",
    seed: "0x8F73·1aa1",
    compute: "504 GPU·h",
    fps: "24",
    resolution: "4096×1716",
    aspect: "2.39:1",
    rating: 4.5,
    color: "#B8651C",
    tone: "warm",
    synopsis: "Three brothers count the days until a debt comes due. Two of them can't read.",
    prompt: "New Mexico high desert, sun-bleached palette, Roger Deakins lighting, sparse dialogue, long takes, period-accurate firearms"
  },
  {
    id: "vesper-arc",
    no: "MT-008",
    title: "Vesper Arc",
    runtime: "112m",
    year: "2026",
    genre: "Sci-Fi",
    model: "Sora-3.2",
    seed: "0x2204·c8d7",
    compute: "743 GPU·h",
    fps: "24",
    resolution: "4096×1716",
    aspect: "2.39:1",
    rating: 4.3,
    color: "#5C2E6B",
    tone: "cool",
    synopsis: "A generation ship arrives. The arrival was never the point.",
    prompt: "Brutalist habitat interiors, zero-g choreography, Tarkovsky long takes, deep blacks, single light source, no exposition"
  },
  {
    id: "the-letter-c",
    no: "MT-009",
    title: "The Letter C",
    runtime: "6m",
    year: "2026",
    genre: "Animation",
    model: "Kling-2",
    seed: "0xAC44·9011",
    compute: "12 GPU·h",
    fps: "12",
    resolution: "1920×1080",
    aspect: "16:9",
    rating: 4.0,
    color: "#D4A03A",
    tone: "warm",
    synopsis: "A stop-motion meditation on a single curve.",
    prompt: "Hand-painted cels, paper texture, gouache palette, no dialogue, cello drone, pacing of a held breath"
  },
  {
    id: "cellar-door",
    no: "MT-010",
    title: "Cellar Door",
    runtime: "31m",
    year: "2025",
    genre: "Mystery",
    model: "Runway Gen-4",
    seed: "0x6601·44ee",
    compute: "98 GPU·h",
    fps: "24",
    resolution: "3840×2160",
    aspect: "16:9",
    rating: 4.1,
    color: "#2A2A2E",
    tone: "neutral",
    synopsis: "An estate sale. A sealed door. A locksmith with too many opinions.",
    prompt: "Damp Massachusetts farmhouse, overcast natural light, Yorgos Lanthimos framing, deadpan performances, off-center compositions"
  },
  {
    id: "fieldwork",
    no: "MT-011",
    title: "Fieldwork",
    runtime: "65m",
    year: "2026",
    genre: "Documentary",
    model: "Veo-4",
    seed: "0x9933·2bf8",
    compute: "318 GPU·h",
    fps: "24",
    resolution: "3840×2160",
    aspect: "16:9",
    rating: 4.4,
    color: "#6B7544",
    tone: "neutral",
    synopsis: "Linguists record the last 47 speakers of a coastal dialect. The dialect records them back.",
    prompt: "Coastal Pacific Northwest, observational ethnography, handheld but composed, ambient sound primary, captions in two scripts"
  },
  {
    id: "halogen-summer",
    no: "MT-012",
    title: "Halogen Summer",
    runtime: "88m",
    year: "2026",
    genre: "Romance",
    model: "Sora-3.2",
    seed: "0x10AF·ee29",
    compute: "456 GPU·h",
    fps: "24",
    resolution: "4096×1716",
    aspect: "2.39:1",
    rating: 4.2,
    color: "#E27A8A",
    tone: "warm",
    synopsis: "Two strangers, one Italian gas station, the longest July on record.",
    prompt: "Sun-saturated Italian provincial town, Call Me By Your Name palette, 35mm warm grain, lingering medium shots, diegetic radio"
  },
  {
    id: "the-quiet-format",
    no: "MT-013",
    title: "The Quiet Format",
    runtime: "14m",
    year: "2026",
    genre: "Experimental",
    model: "Pika-2 / Kling-2",
    seed: "0x4F02·a8c1",
    compute: "44 GPU·h",
    fps: "30",
    resolution: "2880×2160",
    aspect: "4:3",
    rating: 3.8,
    color: "#9B9B92",
    tone: "neutral",
    synopsis: "A test pattern develops a sense of self.",
    prompt: "SMPTE color bars, slow drift toward landscape, CRT phosphor glow, analog warmth, Brian Eno soundscape"
  },
  {
    id: "north-of-rain",
    no: "MT-014",
    title: "North of Rain",
    runtime: "102m",
    year: "2025",
    genre: "Drama",
    model: "Veo-4 / Sora-3.2",
    seed: "0x7878·31aa",
    compute: "611 GPU·h",
    fps: "24",
    resolution: "4096×1716",
    aspect: "2.39:1",
    rating: 4.6,
    color: "#3F5060",
    tone: "cool",
    synopsis: "A retired ferry captain agrees to one last crossing for a passenger who has no luggage.",
    prompt: "Scottish ferry routes, gunmetal sea, sparse score, hands as primary subject, dialogue in three languages"
  },
  {
    id: "telegraph-hill",
    no: "MT-015",
    title: "Telegraph Hill",
    runtime: "19m",
    year: "2026",
    genre: "Period",
    model: "Sora-3.2",
    seed: "0xC011·558d",
    compute: "76 GPU·h",
    fps: "24",
    resolution: "3840×2160",
    aspect: "16:9",
    rating: 4.0,
    color: "#9C7244",
    tone: "warm",
    synopsis: "1906. A boy delivers a message twenty minutes before the earthquake.",
    prompt: "Pre-quake San Francisco, hand-tinted photographic palette, period costumes, silent-film pacing, intertitles"
  },
  {
    id: "argon-sleep",
    no: "MT-016",
    title: "Argon Sleep",
    runtime: "56m",
    year: "2026",
    genre: "Sci-Fi / Slow",
    model: "Veo-4",
    seed: "0xEE99·02b4",
    compute: "289 GPU·h",
    fps: "24",
    resolution: "4096×1716",
    aspect: "2.39:1",
    rating: 4.3,
    color: "#4A6678",
    tone: "cool",
    synopsis: "The night shift at a cryogenic storage facility, told in real time.",
    prompt: "Sterile blue corridors, fluorescent hum, security-camera framing, no music, footsteps as score"
  }
];

window.FILMS = FILMS;
