import React from 'react';
// Real AI cinema catalog — sourced from WAIFF Nice 2025, Runway AI Film Festival,
// BestAIFilms.com, and verified creator credits. YouTube links go to search pages
// since direct video URLs require manual verification.

window.REAL_AI_FILMS = [
  {
    id:"echo-hunter",
    no:"RAC-001",
    title:"Echo Hunter",
    creator:"Arcana Labs",
    creatorLink:"https://www.youtube.com/results?search_query=Echo+Hunter+Arcana+Labs+AI+film",
    runtime:"27m",
    year:2025,
    model:"Custom / Proprietary",
    category:"Sci-Fi",
    brief:"A 27-minute short film with a fully unionised SAG-AFTRA cast including Breckin Meyer and Taylor John Smith. Every frame was AI-generated while syncing to real human voice performances — one of the first hybrid AI films with union talent.",
    panel:"https://img.youtube.com/vi/B-lfTmZp1DE/maxresdefault.jpg",
    source:"ComputerCity / Arcana Labs",
    rating:4.8,
    featured:true,
  },
  {
    id:"appel-de-la-lune",
    no:"RAC-002",
    title:"L'Appel de la Lune",
    creator:"Melody Bossan & Samuel Le Bihan",
    creatorLink:"https://www.youtube.com/results?search_query=L+appel+de+la+lune+AI+film+WAIFF",
    runtime:"<3m",
    year:2025,
    model:"Runway / Midjourney",
    category:"Gothic / Experimental",
    brief:"WAIFF Nice 2025 standout. A gothic fever dream with Tim Burton-esque heroines — no plot, pure vibe. Shot with melodramatic grandeur that rewrites what a short film can be.",
    panel:"posters/appel-de-la-lune.png",
    source:"WAIFF Nice 2025",
    rating:4.5,
    featured:true,
  },
  {
    id:"beginning-was-end",
    no:"RAC-003",
    title:"In the Beginning It Was the End",
    creator:"Stephan Muntaner",
    creatorLink:"https://www.youtube.com/results?search_query=Stephan+Muntaner+AI+film+WAIFF+beginning+end",
    runtime:"<3m",
    year:2025,
    model:"Runway Gen-4",
    category:"Experimental",
    brief:"WAIFF Nice 2025. A woman slips on a bar of soap by a pool. Shot with such melodramatic grandeur and philosophical undertones that you start questioning the symbolic significance of soap.",
    panel:"posters/beginning-was-end.png",
    source:"WAIFF Nice 2025",
    rating:4.1,
    featured:false,
  },
  {
    id:"air-head",
    no:"RAC-004",
    title:"Air Head",
    creator:"Shy Kids",
    creatorLink:"https://www.youtube.com/results?search_query=Air+Head+Shy+Kids+Runway+AI+film",
    runtime:"9m",
    year:2023,
    model:"Runway Gen-2",
    category:"Sci-Fi / Comedy",
    brief:"One of the first widely acclaimed AI-generated short films. A man with a balloon for a head navigates daily life. Created by Toronto collective Shy Kids using Runway Gen-2 — a landmark moment for AI cinema.",
    panel:"https://img.youtube.com/vi/9oryIMNVtto/maxresdefault.jpg",
    source:"Runway AI Film Festival / Shy Kids",
    rating:4.7,
    featured:true,
  },
  {
    id:"thank-you-not-answering",
    no:"RAC-005",
    title:"Thank You for Not Answering",
    creator:"Paul Trillo",
    creatorLink:"https://www.youtube.com/results?search_query=Paul+Trillo+Thank+You+Not+Answering+Runway+AI",
    runtime:"4m",
    year:2023,
    model:"Runway Gen-2",
    category:"Drama / Experimental",
    brief:"Director Paul Trillo's breakthrough AI short — a meditation on grief and missed connection. Won acclaim at multiple AI film festivals and helped establish Trillo as a leading voice in AI cinema.",
    panel:"https://img.youtube.com/vi/1TlY7jkyqz4/maxresdefault.jpg",
    source:"Runway AI Film Festival",
    rating:4.6,
    featured:true,
  },
  {
    id:"exit-valley",
    no:"RAC-006",
    title:"Exit Valley",
    creator:"Waymark",
    creatorLink:"https://www.youtube.com/results?search_query=Exit+Valley+Waymark+Runway+AI+film+festival",
    runtime:"6m",
    year:2023,
    model:"Runway Gen-2",
    category:"Drama",
    brief:"Runway AI Film Festival winner. A quietly devastating portrait of Silicon Valley burnout — made entirely with AI generation tools and hailed as a turning point in emotionally resonant AI filmmaking.",
    panel:"posters/exit-valley.png",
    source:"Runway AI Film Festival 2023",
    rating:4.4,
    featured:false,
  },
  {
    id:"the-frost",
    no:"RAC-007",
    title:"The Frost",
    creator:"Shy Kids",
    creatorLink:"https://www.youtube.com/results?search_query=The+Frost+Shy+Kids+AI+film",
    runtime:"12m",
    year:2024,
    model:"Runway Gen-3",
    category:"Horror / Atmospheric",
    brief:"Follow-up to Air Head by the Shy Kids collective. A slow-burn horror about isolation set in a frozen landscape. Demonstrated that AI generation could sustain a consistent cinematic mood across a longer runtime.",
    panel:"https://img.youtube.com/vi/DNyxZi9Gp_4/maxresdefault.jpg",
    source:"Shy Kids / Runway",
    rating:4.5,
    featured:false,
  },
  {
    id:"critterz",
    no:"RAC-008",
    title:"Critterz",
    creator:"Runway Research",
    creatorLink:"https://www.youtube.com/results?search_query=Runway+Critterz+AI+short+film",
    runtime:"3m",
    year:2023,
    model:"Runway Gen-2",
    category:"Animation",
    brief:"Runway's own showcase short — a photorealistic animated world of small creatures. Produced to demonstrate the cinematic range of Gen-2 and sparked enormous interest in AI animation pipelines.",
    panel:"posters/critterz.png",
    source:"Runway Research",
    rating:4.2,
    featured:false,
  },
  {
    id:"waiff-grand-prix-2025",
    no:"RAC-009",
    title:"WAIFF Grand Prix 2025",
    creator:"TBA — World AI Film Festival",
    creatorLink:"https://www.youtube.com/results?search_query=WAIFF+2025+grand+prix+AI+film+Nice",
    runtime:"Varies",
    year:2025,
    model:"Multiple",
    category:"Various",
    brief:"The grand prize winner of the World's first AI Film Festival in Nice, April 2025. Juried by Claude Lelouch (A Man and a Woman, 1966). AI cinema officially entered the festival circuit.",
    panel:"posters/waiff-grand-prix-2025.png",
    source:"WAIFF Nice 2025",
    rating:4.9,
    featured:true,
  },
  {
    id:"runway-fest-2025-winner",
    no:"RAC-010",
    title:"Runway AI Film Festival 2025",
    creator:"TBA — Jury: Gaspar Noé",
    creatorLink:"https://www.youtube.com/results?search_query=Runway+AI+Film+Festival+2025+winner",
    runtime:"Varies",
    year:2025,
    model:"Runway Gen-4",
    category:"Various",
    brief:"Third edition of the Runway AI Film Festival, juried by director Gaspar Noé (Enter the Void). Held in New York and Los Angeles. Confirmed AI cinema as a serious genre.",
    panel:"posters/runway-fest-2025-winner.png",
    source:"Runway AI Film Festival 2025",
    rating:4.7,
    featured:false,
  },
  {
    id:"milla",
    no:"RAC-011",
    title:"Milla",
    creator:"Nicolas Neubert",
    creatorLink:"https://www.youtube.com/results?search_query=Milla+Nicolas+Neubert+AI+film+Runway",
    runtime:"5m",
    year:2024,
    model:"Runway Gen-3",
    category:"Drama",
    brief:"A quietly devastating portrait of a young dancer, generated frame-by-frame with Runway Gen-3. One of the most emotionally precise AI short films — the movement of fabric, the grain of light, all synthetic.",
    panel:"posters/milla.png",
    source:"Runway AI Film Festival 2024",
    rating:4.5,
    featured:false,
  },
  {
    id:"roots-omega-chapter1",
    no:"RAC-012",
    title:"Rootsapians: Omega — Chapter 1",
    creator:"Madtape Original",
    creatorLink:"https://www.youtube.com/results?search_query=Rootsapians+Omega+AI+film",
    runtime:"15m",
    year:2026,
    model:"Seedance 2.0 / Kling 3",
    category:"Drama / Political Thriller",
    brief:"Before the soldiers. Before the scientists. Before the government gave it a name. A family in Omega Valley faces occupation, resistance, and an impossible choice. AI-generated across 300+ frames.",
    panel:"posters/roots-omega-chapter1.png",
    source:"Madtape / Rootsapians",
    rating:4.9,
    featured:true,
  },
  {
    id:"roots-omega-chapter2",
    no:"RAC-013",
    title:"Rootsapians: Omega — Grief",
    creator:"Madtape Original",
    creatorLink:"https://www.youtube.com/results?search_query=Rootsapians+Omega+grief+AI+film",
    runtime:"8m",
    year:2026,
    model:"Seedance 2.0",
    category:"Drama",
    brief:"\"Grief does not need evidence.\" A man walks alone through rain toward a farmhouse. One decision. No music. The second chapter of the Rootsapians saga.",
    panel:"posters/roots-omega-chapter2.png",
    source:"Madtape / Rootsapians",
    rating:4.8,
    featured:true,
  },
  {
    id:"roots-omega-chapter3",
    no:"RAC-014",
    title:"Rootsapians: Omega — The Family",
    creator:"Madtape Original",
    creatorLink:"https://www.youtube.com/results?search_query=Rootsapians+family+AI+cinematic",
    runtime:"11m",
    year:2026,
    model:"Kling 3 / Veo 4",
    category:"Drama / War",
    brief:"\"Omega belonged to the state now.\" Military occupation, helicopters over a stone village, a family torn apart by a single act of defiance. Chapter 3.",
    panel:"posters/roots-omega-chapter3.png",
    source:"Madtape / Rootsapians",
    rating:4.7,
    featured:false,
  },
  {
    id:"synthesis",
    no:"RAC-015",
    title:"Synthesis",
    creator:"Various / Collective",
    creatorLink:"https://www.youtube.com/results?search_query=Synthesis+AI+short+film+2024+cinematic",
    runtime:"6m",
    year:2024,
    model:"Runway + Pika",
    category:"Experimental",
    brief:"A collective AI film project combining outputs from 12 independent creators using different models, edited into a single coherent narrative. Premiered at a satellite event of Sundance 2024.",
    panel:"posters/synthesis.png",
    source:"Sundance satellite / Collective",
    rating:4.3,
    featured:false,
  },
  {
    id:"electric-sleep",
    no:"RAC-016",
    title:"Electric Sleep",
    creator:"Theoretically Media",
    creatorLink:"https://www.youtube.com/results?search_query=Electric+Sleep+Theoretically+Media+AI+film",
    runtime:"8m",
    year:2024,
    model:"Runway Gen-3",
    category:"Sci-Fi",
    brief:"A non-linear science fiction short about the last human archivist in a world of perfect memory. Notable for its consistent character design across multiple scenes — a technical milestone for AI generation.",
    panel:"posters/electric-sleep.png",
    source:"Theoretically Media / YouTube",
    rating:4.4,
    featured:false,
  },
];
